//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2StepsForwardFoundation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string PlaceOfEmployment { get; set; }
        public decimal TotalIncome { get; set; }
        public decimal AmountNeeded { get; set; }
        public bool AppliedBefore { get; set; }
        public Nullable<bool> AssistanceProvided { get; set; }
        public string BillRequestingPayment { get; set; }
        public bool GovernmentAssistance { get; set; }
        public string GovernmentAssistanceDetails { get; set; }
        public string OtherAssistanceAppliedDetails { get; set; }
        public string HouseholdMemberNameAge1 { get; set; }
        public string HouseholdMemberNameAge2 { get; set; }
        public string HouseholdMemberNameAge3 { get; set; }
        public string HouseholdMemberNameAge4 { get; set; }
        public string HouseholdMemberNameAge5 { get; set; }
        public string HouseholdMemberNameAge6 { get; set; }
        public string AssistanceNeedExplanation { get; set; }
        public string OtherFactorsToReview { get; set; }
        public System.DateTime CreationDateTime { get; set; }
    }
}
